# Generated by Django 3.2 on 2022-01-18 19:39

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20211016_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='backlink_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.INVITATIONS_BACKLINK_COMPANY_MODEL),
        ),
    ]
