# Generated by Django 3.2.9 on 2021-12-03 21:19

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20211016_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.INVITATIONS_COMPANY_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
