# Generated by Django 3.2.9 on 2021-12-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_auto_20211203_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
